name: Build Flutter iOS App

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发构建

jobs:
  build:
    runs-on: macos-latest  # 使用 macOS 环境构建

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'  # 您可以指定 Flutter 版本

      # 安装依赖项
      - name: Install dependencies
        run: flutter pub get

      # 构建 iOS 应用（Release 模式，无需签名）
      - name: Build iOS Release App
        run: flutter build ios --release --no-codesign

      # 调试：检查是否生成了归档文件
      - name: Check build directory
        run: |
          ls -l build/ios/archive/

      # 创建 .ipa 文件并导出
      - name: Package .app to .ipa
        run: |
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist

      # 上传 .ipa 文件作为构建产物
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/ipa/Runner.ipa
